'use client';

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "./components/Navigation";
import Footer from "./components/Footer";
import Loading from "./components/Loading";
import { usePathname } from "next/navigation";
import { useState, useEffect } from "react";
import { useSmoothScroll, useAnimations } from "./utils/interactions";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const [isInitialLoad, setIsInitialLoad] = useState(true);

  // Use custom hooks for interactions
  useSmoothScroll();
  useAnimations();

  useEffect(() => {
    // Only show loading on initial load, not on route changes
    const timer = setTimeout(() => {
      setIsInitialLoad(false);
    }, 1500);

    return () => clearTimeout(timer);
  }, []);



  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-sans bg-dark-950 text-dark-100`}
      >
        {/* Show loading only on initial load */}
        {isInitialLoad ? <Loading /> :
          <div className="min-h-screen">
            {/* Navigation */}
            <Navigation currentPath={pathname} />
            <main className="">
              {children}
            </main>
            {/* Footer */}
            <Footer />
          </div>
        }
      </body>
    </html>
  );
}
